"""
ingest/controller.py

Memoryless ingest submission endpoint.

Governing authority: Research Agent Execution Roadmap, Phase 2.
  "IngestController: accepts raw source submissions, assigns batch_id,
   writes to RawMaterialStore."
  "INV-1: Memoryless — IngestController has no awareness of prior batches."

INV-1 enforcement:
  This module does NOT read global_state.json, state.json, or any other
  ledger file. It does NOT call preflight_read, read_global_state,
  read_season_state, or any season/global state function.
  batch_id is received as input — never derived from state.

batch_start flag authority:
  IngestController does NOT call mark_batch_start or set incompleteBatchFlag.
  That authority belongs to MicroBatchScaffold per roadmap separation.

Source material schema:
  Opaque — IngestController validates type only (must be a non-None dict).
  Content schema is owned by the caller.

I/O:
  Delegates all writes to raw_material.store.ingest.
  No direct file I/O in this module.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from infra.ingestion.raw_material.store import ingest as _store_ingest


# ---------------------------------------------------------------------------
# Receipt
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class IngestReceipt:
    """Immutable confirmation returned by submit().

    Attributes:
        batch_id:    The batch_id under which the material was stored.
        ingested_at: ISO-8601 UTC timestamp of the submit() call.
                     Operational metadata only — not stored in the material
                     content dict and not fingerprint-participating.
    """

    batch_id: str
    ingested_at: str


# ---------------------------------------------------------------------------
# Controller
# ---------------------------------------------------------------------------


def submit(
    store_path: str,
    batch_id: str,
    source_material: dict,
) -> IngestReceipt:
    """Accept a source material submission and persist it to RawMaterialStore.

    Memoryless (INV-1): reads no ledger state, derives nothing from prior
    batches. batch_id is the caller's responsibility to generate correctly.

    Args:
        store_path:      Path to the RawMaterialStore JSON file. Caller
                         must ensure the file exists and is initialised.
        batch_id:        Unique batch identifier for this submission.
                         Must be non-empty. Generated by MicroBatchScaffold.
        source_material: Opaque dict of raw source content. Must be a
                         non-None dict. Content schema is caller-owned.

    Returns:
        IngestReceipt with batch_id and submission timestamp.

    Raises:
        ValueError:               batch_id is empty, or source_material is
                                  None or not a dict. Raised before any I/O.
        RawMaterialWriteError:    batch_id already exists in store
                                  (immutability — propagated from store).
        RawMaterialReadError:     store file unreadable or schema invalid
                                  (propagated from store).
        LedgerWriteMismatchError: atomic write read-back failed
                                  (propagated from store).
    """
    # --- Input validation (pre-I/O) -----------------------------------------

    if not batch_id:
        raise ValueError(
            "batch_id must be a non-empty string. "
            "batch_id is generated by MicroBatchScaffold, not IngestController."
        )

    if source_material is None:
        raise ValueError("source_material must not be None")

    if not isinstance(source_material, dict):
        raise ValueError(
            f"source_material must be a dict, got {type(source_material).__name__}"
        )

    # --- Delegate to store (single call) ------------------------------------

    _store_ingest(store_path, batch_id, source_material)

    # --- Return receipt ------------------------------------------------------

    return IngestReceipt(
        batch_id=batch_id,
        ingested_at=datetime.now(timezone.utc).isoformat(),
    )
