"""
ncg/ncg_schema.py
Narrative Critic Gate constants and schema/version metadata.
"""

from __future__ import annotations

import re

NCG_VERSION: str = "NCG-1.0"
NCG_AUDIT_SCHEMA_VERSION: str = "NCG_AUDIT-1.0"

VERDICT_PASS: str = "PASS"
VERDICT_FAIL: str = "FAIL"

REASON_PASS_ALL_NCG_CHECKS: str = "PASS_ALL_NCG_CHECKS"
REASON_FAIL_MISSING_CLASSIFICATION: str = "FAIL_NCG_MISSING_CLASSIFICATION"
REASON_FAIL_INVALID_SUBCLASS: str = "FAIL_NCG_INVALID_SUBCLASS"
REASON_FAIL_MISSING_TIMESTAMP_CONTEXT: str = "FAIL_NCG_MISSING_TIMESTAMP_CONTEXT"
REASON_FAIL_MISSING_EVENT_DESCRIPTION: str = "FAIL_NCG_MISSING_EVENT_DESCRIPTION"
REASON_FAIL_MISSING_SOURCE_REFERENCE: str = "FAIL_NCG_MISSING_SOURCE_REFERENCE"

STAGE_1_CLASSIFICATION: str = "1_CLASSIFICATION_GATE"
STAGE_2_SUBCLASS: str = "2_SUBCLASS_GATE"
STAGE_3_TIMESTAMP_CONTEXT: str = "3_TIMESTAMP_CONTEXT_GATE"
STAGE_4_EVENT_DESCRIPTION: str = "4_EVENT_DESCRIPTION_GATE"
STAGE_5_SOURCE_REFERENCE: str = "5_SOURCE_REFERENCE_GATE"

_REASON_CODES = (
    REASON_PASS_ALL_NCG_CHECKS,
    REASON_FAIL_MISSING_CLASSIFICATION,
    REASON_FAIL_INVALID_SUBCLASS,
    REASON_FAIL_MISSING_TIMESTAMP_CONTEXT,
    REASON_FAIL_MISSING_EVENT_DESCRIPTION,
    REASON_FAIL_MISSING_SOURCE_REFERENCE,
)

for _code in _REASON_CODES:
    assert isinstance(_code, str)
    assert _code != ""
    assert re.match(r"^[A-Z0-9_]+$", _code)

assert NCG_VERSION == "NCG-1.0"
assert NCG_AUDIT_SCHEMA_VERSION == "NCG_AUDIT-1.0"
